# (C) Copyright 2025- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

"""Integration test: compare plugin regression output against pre-computed HDF5.

This test loads real ERA5 GRIB files from disk and checks that the
RegressionPerturbationPlugin produces the same perturbation arrays as
the reference HDF5 file generated by regression_initial_condition.py.

Requires:
  - ERA5 GRIB files at DATA_PATH
  - Reference HDF5 at H5_PATH
  - scipy, h5py, earthkit-data
"""

from typing import cast

import h5py
import numpy as np
import pytest
from anemoi.inference.context import Context
from pytest_mock import MockerFixture

from anemoi.plugins.ecmwf.inference.dynamics.regression_perturbation import (
    RegressionPerturbationPlugin,
    _gaspari_cohn,
    _haversine,
)

# ---------- paths matching the JAS N320 case ----------
DATA_PATH = "/perm/momc/dynamic_2/dynamical_tests/data_prep/jas_data_aifs/"
H5_PATH = "/perm/momc/dynamic_2/dynamical_tests/data_prep/outputs/n320_nonzero_hurricane_aifs_JAS_15N_40W_regression_red.h5"

# Parameters that produced the HDF5 reference
PARAM_PL = ["z", "q", "t", "u", "v", "w"]
LEVEL_PL = [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50]
PARAM_SFC = ["msl", "10u", "10v", "2t"]
SEASON = "JAS"
YLAT = 15.0
XLON = 320.0  # 360 - 40
XLEV = 5
LOCRAD = 1000.0
AMP = -1.0
FILE_GLOB_SUFFIX = "_n320.grib"
ERA5_GRID = "N320"


# ---- unit tests for helpers ----


class TestHaversine:
    def test_zero_distance(self):
        assert _haversine(0, 0, 0, 0) == pytest.approx(0.0, abs=1e-10)

    def test_quarter_circumference(self):
        # 90 degrees along a meridian ≈ 10007 km
        d = _haversine(0, 0, 0, 90)
        assert 9900 < d < 10100

    def test_symmetry(self):
        d1 = _haversine(10, 20, 30, 40)
        d2 = _haversine(30, 40, 10, 20)
        np.testing.assert_allclose(d1, d2, rtol=1e-10)


class TestGaspariCohn:
    def test_max_at_center(self):
        lat = np.linspace(-90, 90, 500)
        lon = np.linspace(0, 360, 500)
        cov = _gaspari_cohn(lat, lon, 250, 250, 2000.0)
        assert cov[250] == pytest.approx(1.0)

    def test_zero_far_away(self):
        lat = np.linspace(-90, 90, 500)
        lon = np.linspace(0, 360, 500)
        cov = _gaspari_cohn(lat, lon, 250, 250, 100.0)
        # points far from center should be zero
        assert cov[0] == 0.0
        assert cov[-1] == 0.0

    def test_no_negatives(self):
        lat = np.linspace(-90, 90, 1000)
        lon = np.linspace(0, 360, 1000)
        cov = _gaspari_cohn(lat, lon, 500, 500, 3000.0)
        assert np.all(cov >= 0.0)


# ---- integration test against H5 reference ----


@pytest.mark.skipif(
    not all(
        __import__("os").path.exists(p) for p in [DATA_PATH, H5_PATH]
    ),
    reason="ERA5 data or reference HDF5 not available on this machine",
)
class TestRegressionVsH5:
    """Compare the plugin's _compute_regression output against the reference HDF5."""

    @pytest.fixture(scope="class")
    def h5_data(self):
        with h5py.File(H5_PATH, "r") as f:
            return {
                "regf_pl": f["regf_pl"][:],
                "regf_sfc": f["regf_sfc"][:],
                "nonzeros": f["nonzeros"][:],
                "lat": f["lat"][:],
                "lon": f["lon"][:],
            }

    @pytest.fixture(scope="class")
    def plugin_result(self, class_mocker):
        """Run the plugin regression once for all tests in the class."""
        context = cast(Context, class_mocker.MagicMock())
        plugin = RegressionPerturbationPlugin(
            context=context,
            season=SEASON,
            data_path=DATA_PATH,
            era5_grid=ERA5_GRID,
            ylat=YLAT,
            xlon=XLON,
            xlev=XLEV,
            locrad=LOCRAD,
            amp=AMP,
            param_pl=PARAM_PL,
            level_pl=LEVEL_PL,
            param_sfc=PARAM_SFC,
            method="add",
            file_glob_suffix=FILE_GLOB_SUFFIX,
            grid=ERA5_GRID,  # same grid, no regridding
        )
        return plugin._compute_regression()

    def test_pl_keys_present(self, plugin_result):
        for p in PARAM_PL:
            for lev in LEVEL_PL:
                assert (p, lev) in plugin_result, f"Missing key ({p}, {lev})"

    def test_sfc_keys_present(self, plugin_result):
        for p in PARAM_SFC:
            assert (p, None) in plugin_result, f"Missing key ({p}, None)"

    def test_pl_values_match(self, plugin_result, h5_data):
        """Check that PL regression values at nonzero indices match H5."""
        nonzeros = h5_data["nonzeros"]
        regf_pl_h5 = h5_data["regf_pl"]

        for vi, param in enumerate(PARAM_PL):
            for ki, lev in enumerate(LEVEL_PL):
                plugin_full = plugin_result[(param, lev)]
                plugin_sparse = plugin_full[nonzeros]
                h5_sparse = regf_pl_h5[vi, ki, :]
                np.testing.assert_allclose(
                    plugin_sparse,
                    h5_sparse,
                    rtol=1e-5,
                    atol=1e-8,
                    err_msg=f"PL mismatch for {param} at level {lev}",
                )

    def test_sfc_values_match(self, plugin_result, h5_data):
        """Check that SFC regression values at nonzero indices match H5."""
        nonzeros = h5_data["nonzeros"]
        regf_sfc_h5 = h5_data["regf_sfc"]

        for vi, param in enumerate(PARAM_SFC):
            plugin_full = plugin_result[(param, None)]
            plugin_sparse = plugin_full[nonzeros]
            h5_sparse = regf_sfc_h5[vi, :]
            np.testing.assert_allclose(
                plugin_sparse,
                h5_sparse,
                rtol=1e-5,
                atol=1e-8,
                err_msg=f"SFC mismatch for {param}",
            )

    def test_zeros_outside_localization(self, plugin_result, h5_data):
        """Check that perturbation is zero outside the nonzero indices."""
        nonzeros = set(h5_data["nonzeros"].tolist())
        n_gridpoints = len(h5_data["lat"])
        # check a sample PL field
        full = plugin_result[(PARAM_PL[0], LEVEL_PL[5])]
        assert len(full) == n_gridpoints
        zero_mask = np.ones(n_gridpoints, dtype=bool)
        zero_mask[list(nonzeros)] = False
        np.testing.assert_array_equal(
            full[zero_mask],
            0.0,
            err_msg="Non-zero values found outside localization region",
        )

    def test_nonzeros_indices_match(self, plugin_result, h5_data):
        """The set of non-zero indices should match the H5 reference."""
        h5_nz = set(h5_data["nonzeros"].tolist())
        # derive nonzeros from plugin output
        full = plugin_result[(PARAM_PL[0], LEVEL_PL[5])]
        plugin_nz = set(np.nonzero(full)[0].tolist())
        assert plugin_nz == h5_nz
